spring:
#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_mutual_platform?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
server:
  port: 8080
#image:
#  location: C:/Users/Administrator/Desktop/Mp/mutualPlatform/src/main/resources/static/articleImg/




